LuftbornTest/LuftbornTest.AppAdmin/Controllers/DepartmentController.cs
using AutoMapper;
using Entity.AppModel;
using LuftbornTest.AppAdmin.Filter;
using LuftbornTest.AppAdmin.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Repository;

namespace LuftbornTest.AppAdmin.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly UnitOfWork UOW;
        private readonly IMapper mapper;
        public DepartmentController(UnitOfWork UOW,IMapper mapper)
        {
            this.UOW = UOW;
            this.mapper = mapper;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View(UOW.DepartmentRepository.GetAll());
        }
        public IActionResult CreateOrEdit(int Id)
        {
            DepartmentVM departmentVM = new DepartmentVM();
            if (Id > 0)
            {
                Department department = UOW.DepartmentRepository.GetById(Id);
                mapper.Map(department, departmentVM);
                

            }
            return View(departmentVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrEdit(int id,DepartmentVM departmentVM)
        {
            if (ModelState.IsValid)
            {
                Department department = new Department();
                if (id > 0)
                {
                    department = UOW.DepartmentRepository.GetById(id);
                    mapper.Map(departmentVM, department);
                    UOW.DepartmentRepository.UpdateEntity(department);
                    UOW.DepartmentRepository.SaveChanges();
                }
                else
                {
                   
                    mapper.Map(departmentVM, department);
                    UOW.DepartmentRepository.CreateEntity(department);
                    UOW.DepartmentRepository.SaveChanges();
                    
                }
                return RedirectToAction(nameof(Index));
            }
            return View(departmentVM);
            
        }

        public IActionResult Details(int id)
        {
            Department department = UOW.DepartmentRepository.GetById(id);
           
            return View(department);
        }
        public IActionResult Delete(int id)
        {
            Department department = UOW.DepartmentRepository.GetById(id);

            return View(department); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDelete(int id)
        {
            Department department=  UOW.DepartmentRepository.GetById(id);
            UOW.DepartmentRepository.Delete(department);
            UOW.DepartmentRepository.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

LuftbornTest/LuftbornTest.AppAdmin/Controllers/EmployeeController.cs
using AutoMapper;
using DAL;
using Entity.AppModel;
using LuftbornTest.AppAdmin.Filter;
using LuftbornTest.AppAdmin.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Repository;

namespace LuftbornTest.AppAdmin.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly DataContext DB;
        private readonly UnitOfWork UOW;
        private readonly IMapper mapper;
        public EmployeeController(DataContext DB,UnitOfWork UOW,IMapper mapper)
        {
            this.DB = DB;
            this.UOW = UOW;
            this.mapper = mapper;
        }
        [Authorize]
        public IActionResult Index()
        {
            return View(UOW.EmployeeRepository.GetAll());
        }
        public IActionResult CreateOrEdit(int id)
        {
            EmployeeVM employeeVM = new EmployeeVM();
            ViewBag.Genders = new SelectList(UOW.GenderRepository.GetAll(), "Id", "Name");
            ViewBag.Departments = new SelectList(UOW.DepartmentRepository.GetAll(), "Id", "Name");
            if (id > 0)
            {
                Employee employee = UOW.EmployeeRepository.GetById(id);
                mapper.Map(employee, employeeVM);
                employeeVM.Id = id;
                employeeVM.ConfirmPassword = employee.Password;
            }

            return View(employeeVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrEdit(int id,EmployeeVM employeeVM)
        {
            if (ModelState.IsValid)
            {
                Employee employee = new Employee();
                if (id > 0)
                {
                    employee = UOW.EmployeeRepository.GetById(id);
                    mapper.Map(employeeVM, employee);
                    UOW.EmployeeRepository.UpdateEntity(employee);
                    UOW.EmployeeRepository.SaveChanges();
                }
                else
                {
                    mapper.Map(employeeVM, employee);
                    UOW.EmployeeRepository.CreateEntity(employee);
                    UOW.EmployeeRepository.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Genders = new SelectList(UOW.GenderRepository.GetAll(), "Id", "Name");
            ViewBag.Departments = new SelectList(UOW.DepartmentRepository.GetAll(), "Id", "Name");

            return View(employeeVM);
        }

        public IActionResult Details(int id)
        {
            Employee employee = UOW.EmployeeRepository.GetById(id);
            return View(employee);
        }
        public IActionResult Delete(int id)
        {
            Employee employee = UOW.EmployeeRepository.GetById(id);
            return View(employee);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ConfirmDelete(int id)
        {
            Employee employee = UOW.EmployeeRepository.GetById(id);
            UOW.EmployeeRepository.Delete(employee);
            UOW.EmployeeRepository.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

LuftbornTest/LuftbornTest.AppAdmin/Controllers/LoginController.cs
using Entity.AuthModel;
using Microsoft.AspNetCore.Mvc;
using Repository;

namespace LuftbornTest.AppAdmin.Controllers
{
    public class LoginController : Controller
    {
        private readonly ISession session;
        private readonly UnitOfWork UOW;
        public LoginController(IHttpContextAccessor httpContextAccessor ,UnitOfWork UOW)
        {
            session = httpContextAccessor.HttpContext.Session;
            this.UOW = UOW;

        }
        public IActionResult Index()
        {
            session.Clear();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(SystemUser systemUser)
        {
           

            if (UOW.systemUserRepository.UserExist(systemUser.Email, systemUser.Password))
            {
                systemUser = UOW.systemUserRepository.GetByEmail(systemUser.Email);
                session.SetString("Email", systemUser.Email);
                session.SetString("FullName", systemUser.FullName);
                session.SetString("JobTitle", systemUser.JobTitle);
                return RedirectToAction(nameof(Index), "Home");
            }
            ViewData["Error"] = "Email Or Password Are Wrong, Or Account is Deactivated";
          
            return View(systemUser);
        }
        public IActionResult Logout()
        {
            return RedirectToAction(nameof(Index));
        }
    }
}

LuftbornTest/LuftbornTest.AppAdmin/Views/Shared/_Layout.cshtml
@{
    var FullName = HttpContextAccessor.HttpContext.Session.GetString("FullName");
    var JobTitle = HttpContextAccessor.HttpContext.Session.GetString("JobTitle");
    var Email = HttpContextAccessor.HttpContext.Session.GetString("Email");
}

<!DOCTYPE html>
<html class="fixed sidebar-left-collapsed">
<head>
    <!-- Basic -->
    <meta charset="UTF-8">

    <title>@ViewData["Title"] | Admin Panel</title>
    <meta name="keywords" content="App Admin" />
    <meta name="description" content="App Admin">
    <meta name="author" content="App Admin">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@600&display=swap" rel="stylesheet">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Template-Assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/animate/animate.css">

    <link rel="stylesheet" href="~/Template-Assets/vendor/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="~/Template-Assets/vendor/elusive-icons/css/elusive-icons.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/simple-line-icons/css/simple-line-icons.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/meteocons/css/meteocons.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/skins/default.css" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/custom.css">

    <!-- Head Libs -->
    <script src="~/Template-Assets/vendor/modernizr/modernizr.js"></script>

    <style>
        * {
            font-family: 'Cairo', sans-serif;
        }
    </style>
</head>
<body>
    <section class="body">
        <header class="header">
            <div class="logo-container">
                <a asp-controller="Home" asp-action="Index" class="logo">
                    <h2 style="margin-top:0px;"><i class="fas fa-cogs"></i> Admin Panel</h2>
                </a>
                <div class="d-md-none toggle-menu" data-toggle="collapse" data-target=".tab-navigation">
                    <i class="fas fa-bars" aria-label="Toggle Menu"></i>
                </div>
            </div>
            <div class="header-right">
                <span class="separator"></span>
                <div id="userbox" class="userbox">
                    <a href="#" data-toggle="dropdown">
                        <div class="profile-info" data-lock-name="@FullName" data-lock-email="@Email">
                            <span class="name">@FullName</span>
                            <span class="role">@JobTitle</span>
                        </div>
                        <i class="fa custom-caret"></i>
                    </a>
                    <div class="dropdown-menu">
                        <ul class="list-unstyled mb-2">
                            <li class="divider"></li>
                            
                            <li>
                                <a role="menuitem" tabindex="-1" asp-controller="Login" asp-action="Logout"><i class="fas fa-power-off"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <div class="inner-wrapper">
            @{
                await Html.RenderPartialAsync("_Navigation");
            }
            <section role="main" class="content-body">
                <header class="page-header">
                    <h2>@ViewData["Title"]</h2>
                    <div class="right-wrapper text-right">
                        <ol class="breadcrumbs">
                            <li>
                                <a asp-action="Index" asp-controller="Home">
                                    <i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li><span>@ViewData["Title"]</span></li>
                        </ol>

                        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
                    </div>
                </header>
                @RenderBody()
            </section>
        </div>
        <aside id="sidebar-right" class="sidebar-right">
            <div class="nano">
                <div class="nano-content">
                    <a href="#" class="mobile-close d-md-none">
                        Collapse <i class="fas fa-chevron-right"></i>
                    </a>

                    <div class="sidebar-right-wrapper">

                        <div class="sidebar-widget widget-calendar">
                            <h6>Calendar</h6>
                            <div data-plugin-datepicker data-plugin-skin="dark"></div>
                        </div>
                    </div>
                </div>
            </div>
        </aside>
    </section>
    <!-- Vendor -->
    <script src="~/Template-Assets/vendor/jquery/jquery.js"></script>
    <script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Template-Assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Template-Assets/vendor/popper/umd/popper.min.js"></script>
    <script src="~/Template-Assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Template-Assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Template-Assets/vendor/common/common.js"></script>
    <script src="~/Template-Assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="~/Template-Assets/vendor/magnific-popup/jquery.magnific-popup.js"></script>
    <script src="~/Template-Assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Specific Page Vendor -->
    <script src="~/Template-Assets/vendor/jquery-mockjax/jquery.mockjax.js"></script>
    @RenderSection("Scripts",required:false)

    <!-- Theme Base, Components and Settings -->
    <script src="~/Template-Assets/js/theme.js"></script>

    <!-- Theme Custom -->
    <script src="~/Template-Assets/js/custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Template-Assets/js/theme.init.js"></script>
    <script src="~/Template-Assets/js/examples/examples.modals.js"></script>

</body>
</html>

LuftbornTest/LuftbornTest.AppAdmin/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html class="fixed">
<head>
    <meta charset="UTF-8">

    <title>@ViewData["Title"] | Admin Panel</title>

    <meta name="keywords" content="App Admin" />
    <meta name="description" content="App Admin">
    <meta name="author" content="App Admin">
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@600&display=swap" rel="stylesheet">
    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Template-Assets/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/animate/animate.css">

    <link rel="stylesheet" href="~/Template-Assets/vendor/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Template-Assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/skins/default.css" />

    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Template-Assets/css/custom.css">

    <!-- Head Libs -->
    <script src="~/Template-Assets/vendor/modernizr/modernizr.js"></script>

    <style>
        * {
            font-family: 'Cairo', sans-serif;
        }
    </style>
</head>
<body>
    <section class="body-sign">
        <div class="center-sign">
            <div class="panel card-sign">
                <div class="card-title-sign mt-3 text-right">
                    <h2 class="title text-uppercase font-weight-bold m-0"><i class="fas fa-user mr-1"></i>@ViewData["Title"]</h2>
                </div>
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
            <p class="text-center text-muted mt-3 mb-3">&copy; Copyright @DateTime.Now.Year. All Rights Reserved.</p>

        </div>
    </section>
    <!-- end: page -->
    <!-- Vendor -->
    <script src="~/Template-Assets/vendor/jquery/jquery.js"></script>
    <script src="~/Template-Assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Template-Assets/vendor/popper/umd/popper.min.js"></script>
    <script src="~/Template-Assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Template-Assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/Template-Assets/vendor/common/common.js"></script>
    <script src="~/Template-Assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="~/Template-Assets/vendor/magnific-popup/jquery.magnific-popup.js"></script>
    <script src="~/Template-Assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="~/Template-Assets/js/theme.js"></script>

    <!-- Theme Custom -->
    <script src="~/Template-Assets/js/custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/Template-Assets/js/theme.init.js"></script>
    @{
        await Html.RenderPartialAsync("PartialView/_ValidationScriptsPartial");
    }
</body>

</html>

LuftbornTest/LuftbornTest.AppAdmin/Views/Shared/_Navigation.cshtml
<!-- start: sidebar -->
<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">
        <div class="sidebar-title">
            Menu
        </div>
        <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">

                <ul class="nav nav-main">

                    <li>
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fas fa-home" aria-hidden="true"></i>
                            <span>Home</span>
                        </a>
                    </li>

                    <li class="nav-parent">
                        <a class="nav-link" href="#">
                            <i class="fas fa-cogs"></i>
                            <span>Main Data</span>
                        </a>
                        <ul class="nav nav-children">                       
                            <li>
                                <a class="nav-link" asp-controller="Employee" asp-action="Index">
                                    <i class="fas fa-cog"></i>
                                    Employees
                                </a>
                            </li>
                           
                            <li>
                                <a class="nav-link" asp-controller="Department" asp-action="Index">
                                    <i class="fas fa-cog"></i>
                                    Departments
                                </a>
                            </li>
                            
                          
                        </ul>
                    </li>


                </ul>
            </nav>
        </div>

        <script>
            // Maintain Scroll Position
            if (typeof localStorage !== 'undefined') {
                if (localStorage.getItem('sidebar-left-position') !== null) {
                    var initialPosition = localStorage.getItem('sidebar-left-position'),
                        sidebarLeft = document.querySelector('#sidebar-left .nano-content');

                    sidebarLeft.scrollTop = initialPosition;
                }
            }
        </script>


    </div>

</aside>
<!-- end: sidebar -->